// SPDX-License-Identifier: Apache-2.0
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bytes = fs.readFileSync(path.join(root, "rust/target/wasm32-unknown-unknown/release/galaxy_sampler.wasm"));
// An external classic-script payload permits local file:// use without fetch,
// while CSP still requires wasm-unsafe-eval for WebAssembly compilation.
fs.mkdirSync(path.join(root, "wasm"), { recursive: true });
fs.writeFileSync(path.join(root, "wasm/galaxy_sampler.wasm"), bytes);
fs.writeFileSync(path.join(root, "wasm/galaxy-wasm.js"),
  "// SPDX-License-Identifier: Apache-2.0\n// Generated by scripts/build-wasm.sh from rust/src/lib.rs. Do not edit.\n" +
  "globalThis.GALAXY_WASM_BASE64 = " + JSON.stringify(bytes.toString("base64")) + ";\n");
console.log(`Packaged ${bytes.length.toLocaleString("en-US")} bytes of Rust WebAssembly.`);
